### ISSUE TITLE
关于获取原始麦克风信号的问题

### ISSUE THREAD

**Issue by JackyShen007** [respeaker/respeaker_v2_eval#1]
请问用Respeaker的开发板，能否在不用Wake Word的情况下进行声源定位？是否支持连续声源定位？能否获得原始的多路麦克风信号（PCM）？谢谢

**Comment by Pillar1989** [comment]
Yes, you can

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
