### ISSUE TITLE
snowboy hotword spotting for Chinese

### ISSUE THREAD

**Issue by juncaofish** [respeaker/respeaker_v2_eval#2]
I saw it support hand free wake up with snowboy. Does it support Chinese as well? And how? [Wakeup words support for Chinese #1](https://github.com/respeaker/respeaker_python_library/issues/1)

**Comment by xiongyihui** [comment]
Snowboy supports Chinese. You can create your own wake-up word at https://snowboy.kitt.ai

**Comment by juncaofish** [comment]
Of course I know about snowboy, what I mean is does respeaker_v2_eval use a different hardware platform instead of mips so it can support snowboy

**Comment by xiongyihui** [comment]
Yes, it uses Cortex A7 RK3229

**Comment by juncaofish** [comment]
Thanks.
